[workspace]
members = [
    "code-understanding",
    "code-search",
    "ingestion",
    "code-navigator",
    "context-generator",
    "modifier",
    "common",
    "coordinator",
    "ai-gateway"
]
resolver = "2"
