image:
  repository: nginx # To be overridden from GitHub action
  tag: 1.19.3 # To be overridden from GitHub action

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
  host: search.collectivai.com
  tlsEnabled: true

containerPort: 3000

resources:
  limits:
    cpu: "3000m"
    memory: "2000Mi"
  requests:
    cpu: "1000m"
    memory: "1000Mi"